%YAML 1.2
---
cpu: 4
disable_animation: false
exclude: '[./.*, ./__*]'
hardware: CPU
include: '[./*, main.py, requirements.txt, pkglist.txt, conda_pkglist.txt]'
log_level: INFO
memory: 18
min_replicas: 1
