%YAML 1.2
---
cpu: 2
disable_animation: false
exclude: '[./.*, ./__*]'
hardware: AMPERE_A4000
include: '[./*, main.py, requirements.txt, pkglist.txt, conda_pkglist.txt]'
log_level: INFO
memory: 14.5
min_replicas: 1
